# Generated by Django 4.2.18 on 2025-01-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restaurant_restaurant_type_sales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
