# Generated by Django 4.2.18 on 2025-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staff_alter_restaurant_options_alter_rating_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
